# Generated by Django 4.2.15 on 2024-08-29 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0002_profile_socialaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('permission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('type_user', models.ManyToManyField(related_name='aign_permission', to='account.typeuser')),
            ],
        ),
    ]
