# Generated by Django 4.2.15 on 2024-08-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_courses', '0003_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
