# Generated by Django 4.2.15 on 2024-08-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_courses', '0004_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
    ]
