# Generated by Django 4.2.15 on 2024-08-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_courses', '0005_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='api_courses.student'),
        ),
    ]
