# Generated by Django 4.2.15 on 2024-08-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_courses', '0007_remove_student_last_name_remove_student_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
